# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-yq4mZst7EKl-hjLxASuzIMsg2MoM0GX
"""

class Stack:
    def __init__(self, stack):
        self.stack = stack
        return

    def add_element(self, element):
       self.stack.append(element)

    def get_last_element(self):
        if not self.stack is None:
            return self.stack[-1]
        else:
            return None

    def del_last_element(self):
        self.stack.pop(-1)

    def __repr__(self):
        return str(self.stack)

s = Stack([1,2,3,4])

s.get_last_element()